# Generated by Django 4.2.5 on 2023-12-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0002_generatedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcode',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
