# Generated by Django 4.2.5 on 2023-12-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0004_professions_corporatedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedb',
            name='referralCode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
