# Generated by Django 4.2.5 on 2023-12-24 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twamitraApp', '0007_subscriptiontype_remove_corporatepayments_cid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=7, unique=True)),
                ('businessName', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('referralCode', models.CharField(max_length=8, null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('active_till', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twamitraApp.professions')),
                ('subscription_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twamitraApp.subscriptiontype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorporatePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=255)),
                ('razorpay_payment_id', models.CharField(max_length=255)),
                ('razorpay_signature', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twamitraApp.corporatedb')),
                ('subscription_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twamitraApp.subscriptiontype')),
            ],
        ),
    ]
