# Generated by Django 4.2.5 on 2023-12-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0009_alter_corporatedb_active_till'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twamitraApp.professions')),
            ],
        ),
    ]
