# Generated by Django 4.2.5 on 2023-12-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0010_servicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatedb',
            name='referralCode',
        ),
        migrations.AddField(
            model_name='corporatepayments',
            name='referralCode',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='corporatepayments',
            name='referralUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporatepayments',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corporatepayments',
            name='razorpay_payment_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corporatepayments',
            name='razorpay_signature',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
