# Generated by Django 4.2.5 on 2023-12-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0011_remove_corporatedb_referralcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatepayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
