# Generated by Django 5.0.1 on 2024-01-14 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twamitraApp', '0016_loandetail_loantype_delete_loan_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcode',
            name='expiration_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
